apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-db-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: voting-db-pod
        image: postgres:9.4
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config

