apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-worker-deployment
spec:
  selector:
    matchLabels:
      app: voting-worker
  template:
    metadata:
      labels:
        app: voting-worker
    spec:
      containers:
      - name: voting-worker
        image: dockersamples/examplevotingapp_worker
 